project: fast_diffusion
group: ae_ddpm

trainer:
  trainer: AEDDPMTrainer
  out_dir: /home/ok313/outputs/aeddpm
  max_epochs: 200
  pl:
    monitor: val/loss_noise
    log_freq: 50

data:
  data_root: /rds/user/ok313/hpc-work/datasets/
  dataset_cls: CelebaHQColorizationDataset
  dataset: celeba_hq_256
  split: celebahq
  train_batch_size: 64
  val_batch_size: 64
  test_batch_size: 64
  train_workers: 4
  val_workers: 4
  test_workers: 4

model:
  in_ch: 1
  latent_dim: 64
  out_ch: 3
  image_h: 128
  image_w: 128
  encoder_channels: [16, 32, 64, 128, 256]
  decoder_channels: [256, 128, 64, 32, 16]

optimizer:
  optimizer: "adamw"
  lr: 1e-4
  wd: 1e-3
  scheduler: cosine_warmup
  sched_interval: step
  warmup: 10
  

diffusion:
  ema_decay: 0.999
  beta_schedule:
    train:
      schedule: linear
      n_timestep: 2000
      linear_start: 1e-6
      linear_end: 0.01
    test: 
      schedule: linear
      n_timestep: 1000
      linear_start: 1e-4
      linear_end: 0.09