project: fast_diffusion
group: debug

trainer:
  max_epochs: 20
  pl:
    log_freq: 10

model:
  in_ch: 1
  latent_dim: 256
  out_ch: 3
  image_h: 64
  image_w: 64
  encoder_channels: [16, 32, 64, 128, 256]
  decoder_channels: [256, 128, 64, 32, 16]

optimizer:
  optimizer: "adamw"
  lr: 1e-3
  wd: 1e-2
  scheduler: cosine_warmup
  warmup: 2

loss:
  kl_cycle: 10