project: fast_diffusion
group: debug

trainer:
  max_epochs: 20
  pl:
    log_freq: 10

data:
  dataset_cls: CelebaHQColorizationDataset
  dataset: celeba_hq_256
  split: debug
  train_batch_size: 16
  val_batch_size: 10
  test_batch_size: 10
  train_workers: 2
  val_workers: 2
  test_workers: 2

model:
  in_ch: 1
  latent_dim: 512
  out_ch: 3
  image_h: 64
  image_w: 64
  encoder_channels: [16, 32, 64, 128, 256]
  decoder_channels: [256, 128, 64, 32, 16]

optimizer:
  optimizer: "adamw"
  lr: 1e-3
  wd: 1e-2
  scheduler: cosine_warmup
  sched_interval: step
  warmup: 2

loss:
  kl_cycle: 10