project: fast_diffusion
group: simplevae_recon

trainer:
  trainer: SimpleVAETrainer
  out_dir: /home/ok313/outputs/simplevae
  max_epochs: 200
  pl:
    log_freq: 50
    monitor: val/loss

data:
  data_root: /rds/user/ok313/hpc-work/datasets/
  dataset_cls: CelebaHQReconDataset
  dataset: celeba_hq_256
  split: celebahq
  train_batch_size: 128
  val_batch_size: 64
  test_batch_size: 64
  train_workers: 4
  val_workers: 4
  test_workers: 4

model:
  in_ch: 3
  latent_dim: 64
  out_ch: 3
  image_h: 128
  image_w: 128
  encoder_channels: [16, 32, 64, 128, 256]
  decoder_channels: [256, 128, 64, 32, 16]

optimizer:
  optimizer: "adamw"
  lr: 1e-3
  wd: 1e-2
  scheduler: cosine_warmup
  sched_interval: step
  warmup: 5

loss:
  mse_weight: 2.0
  kl_weight: 2.0
  kl_cycle: 25
