project: fast_diffusion
group: transvae

trainer:
  trainer: TranslationVAETrainer
  out_dir: /home/ok313/outputs/transvae
  max_epochs: 100
  pl:
    log_freq: 50
    monitor: val/loss

data:
  data_root: /rds/user/ok313/hpc-work/datasets/
  dataset_cls: CelebaHQColorizationDataset
  dataset: celeba_hq_256
  split: celebahq
  train_batch_size: 32
  val_batch_size: 32
  test_batch_size: 32
  train_workers: 4
  val_workers: 4
  test_workers: 4
  n_bits: 5

model:
  in_ch: 1
  latent_dim: 64
  out_ch: 3
  image_h: 128
  image_w: 128
  encoder_channels: [16, 32, 64, 128, 256]
  decoder_channels: [256, 128, 64, 32, 16]

optimizer:
  optimizer: "adamax"
  lr: 1e-3
  wd: 3e-4
  scheduler: cosine_warmup
  sched_interval: step
  warmup: 5

loss:
  kl_cycle: 25
  kl_weight: 0.2
  l1_weight: 0.5
  trans_vae_cond_weight: 0.5
  affine_weight: 0.2
  spectral_weight: 0.2
