project: fast_diffusion
group: tvae_ddpm

trainer:
  trainer: VAEDDPMTrainer
  out_dir: /home/ok313/outputs/tvaeddpm
  max_epochs: 100
  pl:
    monitor: val/loss_noise
    log_freq: 50

data:
  data_root: /rds/user/ok313/hpc-work/datasets/
  dataset_cls: CelebaHQColorizationDataset
  dataset: celeba_hq_256
  split: celebahq
  train_batch_size: 32
  val_batch_size: 32
  test_batch_size: 32
  train_workers: 4
  val_workers: 4
  test_workers: 4

model:
  in_ch: 1
  latent_dim: 64
  out_ch: 3
  image_h: 128
  image_w: 128
  encoder_channels: [16, 32, 64, 128, 256]
  decoder_channels: [256, 128, 64, 32, 16]

optimizer:
  optimizer: adam
  lr: 5e-5
  wd: 0
  scheduler:

diffusion:
  ae_ckpt: /home/ok313/ckpt/tvae/transvae.ckpt
  concat: True
  beta_schedule:
    train:
      schedule: linear
      n_timestep: 2000
      linear_start: 1e-6
      linear_end: 0.01
    test: 
      schedule: linear
      n_timestep: 1000
      linear_start: 1e-4
      linear_end: 0.09